# Generated by Django 5.0.6 on 2025-03-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_books_genre_remove_books_price_author_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='collection',
            new_name='blogs',
        ),
        migrations.RemoveField(
            model_name='books',
            name='cover',
        ),
    ]
