# Generated by Django 5.0.6 on 2025-03-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_comment_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='books',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
