# Generated by Django 5.0.6 on 2025-03-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_books_options_books_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Blogs',
        ),
    ]
